use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct EditablePathSpec {
    path: String,
    operation: String,
    description: String,
    params: Vec<String>,
    bounds: String,
}

#[derive(Debug, Deserialize)]
struct ElementSpec {
    x: String,
    y: String,
    width: String,
    height: String,
    font_size: Option<i64>,
    bold: Option<bool>,
    image_scaling: Option<String>,
}

#[derive(Debug, Deserialize)]
struct TemplateYaml {
    layout: String,
    #[serde(default)]
    description: String,
    #[serde(default)]
    parameters: BTreeMap<String, f64>,
    editable_paths: Vec<EditablePathSpec>,
    elements: BTreeMap<String, ElementSpec>,
}

fn main() {
    if let Err(err) = generate_template_manifest() {
        panic!("Template engine build step failed: {err}");
    }
}

fn generate_template_manifest() -> Result<(), String> {
    let manifest_dir = Path::new("templates/layouts");
    println!("cargo:rerun-if-changed={}", manifest_dir.display());

    let mut templates: BTreeMap<String, TemplateYaml> = BTreeMap::new();

    for entry in fs::read_dir(manifest_dir)
        .map_err(|e| format!("failed to read templates directory: {e}"))?
    {
        let entry = entry.map_err(|e| format!("failed to read template entry: {e}"))?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("yaml") {
            continue;
        }

        println!("cargo:rerun-if-changed={}", path.display());

        let raw = fs::read_to_string(&path)
            .map_err(|e| format!("failed to read {}: {e}", path.display()))?;

        let parsed: TemplateYaml = serde_yaml::from_str(&raw)
            .map_err(|e| format!("invalid YAML for {}: {e}", path.display()))?;

        if templates.insert(parsed.layout.clone(), parsed).is_some() {
            return Err(format!(
                "duplicate layout definition found in {}",
                path.display()
            ));
        }
    }

    if templates.is_empty() {
        return Err("no templates found under templates/layouts".to_string());
    }

    let out_dir =
        PathBuf::from(std::env::var("OUT_DIR").map_err(|e| format!("OUT_DIR unavailable: {e}"))?);
    let output = out_dir.join("template_manifest.rs");
    fs::write(&output, emit_manifest_module(&templates))
        .map_err(|e| format!("failed to write {}: {e}", output.display()))?;

    Ok(())
}

fn emit_manifest_module(templates: &BTreeMap<String, TemplateYaml>) -> String {
    let mut editable_paths = Vec::new();
    let mut operations = Vec::new();

    for layout in templates.values() {
        for entry in &layout.editable_paths {
            editable_paths.push(entry.path.clone());
            operations.push((
                entry.path.clone(),
                entry.operation.clone(),
                entry.description.clone(),
                entry.params.clone(),
                entry.bounds.clone(),
            ));
        }
    }

    editable_paths.sort();
    editable_paths.dedup();

    let mut output = String::new();
    output.push_str("// @generated by build.rs; do not edit manually.\n");
    output.push_str("pub struct TemplateOperationSpec {\n");
    output.push_str("    pub path: &'static str,\n");
    output.push_str("    pub name: &'static str,\n");
    output.push_str("    pub description: &'static str,\n");
    output.push_str("    pub params: &'static [&'static str],\n");
    output.push_str("    pub bounds: &'static str,\n");
    output.push_str("}\n\n");
    
    output.push_str("pub struct LayoutElement {\n");
    output.push_str("    pub slot: &'static str,\n");
    output.push_str("    pub x: &'static str,\n");
    output.push_str("    pub y: &'static str,\n");
    output.push_str("    pub width: &'static str,\n");
    output.push_str("    pub height: &'static str,\n");
    output.push_str("    pub font_size: Option<i64>,\n");
    output.push_str("    pub bold: Option<bool>,\n");
    output.push_str("    pub image_scaling: &'static str,\n");
    output.push_str("}\n\n");

    output.push_str("pub struct LayoutDefinition {\n");
    output.push_str("    pub layout: &'static str,\n");
    output.push_str("    pub description: &'static str,\n");
    output.push_str("    pub parameters: &'static [(&'static str, f64)],\n");
    output.push_str("    pub elements: &'static [LayoutElement],\n");
    output.push_str("}\n\n");

    output.push_str("pub const TEMPLATE_EDITABLE_PATHS: &[&str] = &[\n");
    for path in editable_paths {
        output.push_str(&format!("    \"{}\",\n", escape_rust_string(&path)));
    }
    output.push_str("];\n\n");

    output.push_str("pub const TEMPLATE_OPERATION_SPECS: &[TemplateOperationSpec] = &[\n");
    for (path, name, description, params, bounds) in operations {
        output.push_str("    TemplateOperationSpec {\n");
        output.push_str(&format!("        path: \"{}\",\n", escape_rust_string(&path)));
        output.push_str(&format!("        name: \"{}\",\n", escape_rust_string(&name)));
        output.push_str(&format!("        description: \"{}\",\n", escape_rust_string(&description)));
        output.push_str("        params: &[");
        for (idx, param) in params.iter().enumerate() {
            if idx > 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("\"{}\"", escape_rust_string(param)));
        }
        output.push_str("],\n");
        output.push_str(&format!("        bounds: \"{}\",\n", escape_rust_string(&bounds)));
        output.push_str("    },\n");
    }
    output.push_str("];\n\n");

    output.push_str("pub const LAYOUT_DEFINITIONS: &[LayoutDefinition] = &[\n");
    for (layout_name, layout) in templates {
        output.push_str("    LayoutDefinition {\n");
        output.push_str(&format!("        layout: \"{}\",\n", escape_rust_string(layout_name)));
        output.push_str(&format!("        description: \"{}\",\n", escape_rust_string(&layout.description)));
        output.push_str("        parameters: &[\n");
        for (param, val) in &layout.parameters {
            output.push_str(&format!("            (\"{}\", {}),\n", escape_rust_string(param), val));
        }
        output.push_str("        ],\n");
        output.push_str("        elements: &[\n");
        for (slot, elem) in &layout.elements {
            output.push_str("            LayoutElement {\n");
            output.push_str(&format!("                slot: \"{}\",\n", escape_rust_string(slot)));
            output.push_str(&format!("                x: \"{}\",\n", escape_rust_string(&elem.x)));
            output.push_str(&format!("                y: \"{}\",\n", escape_rust_string(&elem.y)));
            output.push_str(&format!("                width: \"{}\",\n", escape_rust_string(&elem.width)));
            output.push_str(&format!("                height: \"{}\",\n", escape_rust_string(&elem.height)));
            
            match elem.font_size {
                Some(fs) => output.push_str(&format!("                font_size: Some({}),\n", fs)),
                None => output.push_str("                font_size: None,\n"),
            }
            match elem.bold {
                Some(b) => output.push_str(&format!("                bold: Some({}),\n", b)),
                None => output.push_str("                bold: None,\n"),
            }
            let scaling = elem.image_scaling.as_deref().unwrap_or("contain");
            output.push_str(&format!("                image_scaling: \"{}\",\n", escape_rust_string(scaling)));
            output.push_str("            },\n");
        }
        output.push_str("        ],\n");
        output.push_str("    },\n");
    }
    output.push_str("];\n");

    output
}

fn escape_rust_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}
