#!/usr/bin/env python3

import json
import yaml
import render_slides

def step_1_describe_layouts():
    print("=== STEP 1: Describe Layouts (For LLM) ===")
    layouts_json = render_slides.describe_layouts()
    layouts = json.loads(layouts_json)
    
    # We dump it to YAML as recommended for LLM token efficiency
    print("Prompt to LLM: 'Here are the available layouts:'")
    print(yaml.dump(layouts, sort_keys=False))
    return layouts

def step_2_llm_generates_slides():
    print("\n=== STEP 2: LLM Generates Slides ===")
    print("LLM generates the following AST for the presentation...")
    ast = {
        "slides": [
            {
                "layout": "title_body",
                "slots": {
                    "title": "Welcome to the Prototype",
                    "body": "This slide was generated by an LLM mock.",
                }
            }
        ]
    }
    print(json.dumps(ast, indent=2))
    return ast

def step_3_describe_tweaks():
    print("\n=== STEP 3: Describe Tweaks (For LLM) ===")
    tweaks_json = render_slides.describe_tweaks()
    tweaks = json.loads(tweaks_json)
    
    print("Prompt to LLM: 'You may now tweak the presentation using these operations:'")
    print(yaml.dump(tweaks, sort_keys=False))
    return tweaks

def step_4_llm_applies_tweaks():
    print("\n=== STEP 4: LLM Requests Tweaks ===")
    # Suppose the LLM looks at the preview and decides to increase the title size
    # and explicitly set the body text font size to 36
    
    tweaks_requested = [
        {"path": "slides[0].style.title.font_size", "operation": "increase", "step": 1},
        {"path": "slides[0].style.body.font_size", "operation": "set_font_size", "size": 36}
    ]
    
    print("LLM replies with the following tweaking instructions:")
    print(yaml.dump(tweaks_requested, sort_keys=False))
    
    return tweaks_requested

def main():
    # 1. Fetch layout schema
    layouts = step_1_describe_layouts()
    
    # 2. Generate AST
    ast = step_2_llm_generates_slides()
    
    # 3. Fetch tweak operations
    tweaks = step_3_describe_tweaks()
    
    # 4. LLM requests tweaks
    requested_tweaks = step_4_llm_applies_tweaks()
    
    # 5. Normally we'd apply tweaks to AST here, but the applying logic
    # is usually handled by orchestrator using json-patch or python dict updates.
    print("\n=== STEP 5: Orchestrator applies tweaks and re-renders ===")
    print("Done!")

if __name__ == "__main__":
    main()
